### ISSUE TITLE
Make Callback and Logout URLs Configurable

### ISSUE THREAD

**Issue by jjathman** [pac4j/spring-webmvc-pac4j#16]
I think it would be nice if the request mappings for the `CallbackController` and `LogoutController` were configurable in an easy way. I think it would be a relatively simple change like this one in the  `CallbackController` class.

Change:
`@RequestMapping("/callback")`

to this:
`@RequestMapping("${pac4j.callback.url:/callback}")`

In our environment all applications have tried to use a similar URL scheme for their signout URL so it would be convenient to be able to have a property to define in this case.

**Comment by leleuj** [comment]
Sure. That perfectly makes sense. I thought it was already done. Would you mind submitting a PR for that? It could fit in the 3.0.0 release. Thanks
