### ISSUE TITLE
Allow RequiresAuthenticationInterceptor to specify a redirect

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/spring-webmvc-pac4j#2]
When the interceptor calls forbidden or unauthorized, a status code is set. Allow:

1. The status code to be customizable. Like a 302
2. Add support for a response header key/value pair, such as "Location: AuthZFailed".

**Comment by leleuj** [comment]
Currently, you can do that only by subclassing the interceptor. That said, you can throw a specific `RequiresHttpAction` at the client (or authenticator) level to "break" the flow the way you want...

**Comment by mmoayyed** [comment]
Yes, did the subclassing bit. Of course, would be nice if I could just do that with config rather than relying on API.

**Comment by leleuj** [comment]
Addressed by pac4j v1.9
