### ISSUE TITLE
HTTP GET/POST/PUT/DELETE methods support

### ISSUE THREAD

**Issue by ArkadyKarev** [pac4j/spring-webmvc-pac4j#24]
Looks like there is no http methods support in SecurityInterceptor. I was looking for it to use in my RESTful API, but didn't find. I've created my own implementation, and can create pull request for it, if you would like.

**Comment by leleuj** [comment]
In fact, you can apply the `SecurityInterceptor` only for a specific HTTP Method using the `Matcher` concept and this class: https://github.com/pac4j/pac4j/blob/3.7.x/pac4j-core/src/main/java/org/pac4j/core/matching/HttpMethodMatcher.java
See: http://www.pac4j.org/3.7.x/docs/matchers.html

For a REST API, you may want to use the annotations: `@RequireAnyRole` and `@RequireAllRoles` as I explained in my blog post: http://www.pac4j.org/blog/spring-webmvc-pac4j-vs-spring-security-round-2-rest-apis.html

**Comment by ArkadyKarev** [comment]
I can't use `@RequireAnyRole` nor `@RequireAllRoles` in my case, because I need to provide POST execution for not authenticated clients, and the same endpoint only for authenticated.

For example, at /api/v1/user via POST we are creating new (not authenticated) user, and via GET at the same endpoint we want to retreive current (authenticated) one.

InterceptorRegistration (that part of spring-webmvc) supports only `pathMatcher`, so I see no option to use HttpMethodMatcher.

So my implementation allows me to work with HTTP methods by following example:

```
registry.addInterceptor(new SkintorySecurityInterceptor(config, "CookieClient,FormClient")
		.withMethod(HttpMethod.GET))
		.addPathPatterns(
				"/api/v1/user"
		);
registry.addInterceptor(new SkintorySecurityInterceptor(config, "CookieClient,FormClient")
		.withMethod(HttpMethod.POST))
		.addPathPatterns(
				"/api/v1/routine",
				"/api/v1/product/*/routines",
				"/api/v1/topic/comment",
				"/api/v1/topic/comment/*/vote",
				"/api/v1/product/comment",
				"/api/v1/product/comment/*/vote",
				"/api/v1/product/vote",
				"/api/v1/topic",
				"/api/v1/topic/*/vote",
				"/api/v1/user/note",
				"/api/v1/users/*/shoppingList/*",
				"/api/v1/users/*/subscribe/*"
		);
registry.addInterceptor(new SkintorySecurityInterceptor(config, "CookieClient,FormClient")
		.withMethod(HttpMethod.PUT))
		.addPathPatterns(
				"/api/v1/user",
				"/api/v1/product/*/routines",
				"/api/v1/topic/comment",
				"/api/v1/product/comment",
				"/api/v1/user/note"
		);
registry.addInterceptor(new SkintorySecurityInterceptor(config, "CookieClient,FormClient")
		.withMethod(HttpMethod.DELETE))
		.addPathPatterns(
				"/api/v1/topic/comment/*",
				"/api/v1/topic/comment/*/unvote",
				"/api/v1/product/comment/*",
				"/api/v1/product/comment/*/unvote",
				"/api/v1/topic/*/unvote",
				"/api/v1/user/note/*",
				"/api/v1/users/*/shoppingList/delete/*",
				"/api/v1/users/*/unsubscribe/*"
		);
```
This two great demos contains examples only for GET requests:
https://github.com/pac4j/spring-webmvc-pac4j-boot-demo
https://github.com/pac4j/spring-webmvc-pac4j-demo

If we can put into some examples to help APIs building (and described issue), it will be perfect. And if I can help to you with this, just let me know.

For now I see no options to use HttpMethodMatcher in spring-webmvc :( But it sounds like exactly what I need.

**Comment by leleuj** [comment]
You should create the appropriate matcher in the configuration:

```java
config.addMatcher("postonly", new HttpMethodMatcher(HttpConstants.HTTP_METHOD.POST));
```

and then apply it:

```java
registry.addInterceptor(new SecurityInterceptor(config, "FacebookClient", null, "postonly")).addPathPatterns("/facebook/*");
```

**Comment by ArkadyKarev** [comment]
Brilliant, thank you :)

**Comment by leleuj** [comment]
My only remaining question is whether we should have them as default matchers: https://github.com/pac4j/pac4j/issues/1285

**Comment by ArkadyKarev** [comment]
What do you mean as default, @leleuj?

**Comment by leleuj** [comment]
I mean that you would not need to define these matchers in the configuration, but that they would be available by default. Only: `registry.addInterceptor(new SecurityInterceptor(config, "FacebookClient", null, "post")).addPathPatterns("/facebook/*");`

**Comment by ArkadyKarev** [comment]
Or even maybe `registry.addInterceptor(new SecurityInterceptor(config, "FacebookClient", null, HttpConstants.HTTP_METHOD.POST)).addPathPatterns("/facebook/*")`. Looks great 👍

**Comment by leleuj** [comment]
Yes, that's an option. It's a bit too specific though.

The idea currently is to make it work for all frameworks, so for JEE, we need strings.

Yet, we can make configuration easier. Here is a proposal: https://github.com/pac4j/spring-webmvc-pac4j/pull/25/files and https://github.com/pac4j/spring-webmvc-pac4j-boot-demo/pull/11/files

What do you think?
