### ISSUE TITLE
[Feature request] Liferay support for SAML pac4j

### ISSUE THREAD

**Issue by sytolk** [pac4j/spring-webmvc-pac4j#26]
I think it's easy to use spring webmvc integration for saml-pac4j in Liferay portlet. 
Now Liferay provide SAML plugin but for Enterprice Edition only: https://web.liferay.com/marketplace/-/mp/application/15188711

**Comment by leleuj** [comment]
I'm not sure to understand if you can already use Spring MVC and pac4j-saml in SAML what do you expect?

**Comment by sytolk** [comment]
@leleuj thanks for you comment! I think that sample usage project (like pac4j-liferay-demo) will safe so much time.. and will be very usefull for Liferay users.
Liferay 7 uses the OSGi standard but pac4j and it's transitive dependencies are not OSGI bundles (with some exceptions like guava). If we want to use this library in Liferay it's need to build a service to encapsulate the services the dependency jar provides. That way we can have a separate API module that bundles can depend on and use, and also get an implementation module that has the embedded jar. This way embed the jar, but only in a single module. 
I have try this but Liferay's compileOnly and compileInclude Gradle tasks failed to deals with transitive dependencies.. in generated manifest file its have:
```
Import-Package: com.sun.msv.grammar,com.sun.msv.grammar.trex,com.sun.msv.grammar.xmlschema,com.sun.msv.rea
 der,com.sun.msv.reader.trex.ng,com.sun.msv.reader.util,com.sun.msv.re
 ader.xmlschema,com.sun.msv.util,com.sun.msv.verifier,com.sun.msv.veri
 fier.regexp,com.sun.msv.verifier.regexp.xmlschema
```

maybe jaxb dependency? but I cant find it in transitive.. and if I try to deploy bundle service:
 
```
2019-06-03 17:51:04.268 ERROR [fileinstall-/opt/liferay/osgi/modules][org_apache_felix_fileinstall:97] Error while starting bundle: file:/opt/liferay/osgi/modules/de.kv.pac4j.services.saml.impl-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: de.kv.pac4j.services.saml.impl [999]_  Unresolved requirement: Import-Package: com.sun.msv.grammar_ [Sanitized]
```

**Comment by mmoayyed** [comment]
We have no plans to build such a thing. If you are interested, a pull request would be very welcome.
