### ISSUE TITLE
Upgrade to pac4j v1.9

### ISSUE THREAD

**Issue by leleuj** [pac4j/spring-webmvc-pac4j#5]
and all dependencies, Java 8...
Rename `RequiresAuthenticationInterceptor` as `SecurityInterceptor`

**Comment by mmoayyed** [comment]
Just noting that this issue is a requirement for CAS to upgrade to pac4j 1.9

**Comment by leleuj** [comment]
Indeed

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/spring-webmvc-pac4j/pull/6 and demos: https://github.com/pac4j/spring-webmvc-pac4j-demo/pull/1 + https://github.com/pac4j/spring-webmvc-pac4j-boot-demo/pull/3

**Comment by leleuj** [comment]
@mmoayyed : I released the version 1.1.0, so we will be able to upgrade CAS. For the OAuth / OpenID Connect support as well as for the management webapp, it should be straightforward (`RequiresAuthenticationInterceptor` becomes `SecurityInterceptor`).  Things should be a little more complicated for "authentication delegation" due to the cleaning in pac4j v1.9 of the "direct/ indirect" concept.

**Comment by mmoayyed** [comment]
Most excellent. 

I am sure I have a branch somewhere that starts off with 1.9 at some point. We could collaborate there together, once I find it. My goal was to add support for digest authN into CAS, thus the 1.9 upgrade but then I realized we could and should probably fix a few other things before we can get digest authN working again. 

I'll post the branch address back on the issue on CAS.

**Comment by leleuj** [comment]
OK. Don't worry if you don't see me around in the next two weeks, I'm in holidays...

**Comment by mmoayyed** [comment]
Sure thing. Enjoy.
