### ISSUE TITLE
Consider renaming artifact to `pac4j-spring-webmvc`

### ISSUE THREAD

**Issue by snicoll** [pac4j/spring-webmvc-pac4j#7]
Thanks for the Spring support in pac4j. Could you please avoid naming your artifacts with the same root as the ones of the Spring Framework? `spring-webmvc` is an artifact of the Spring Framework and this module sounds like it was an official extension of it. 

Thanks.

**Comment by leleuj** [comment]
It's a general convention in pac4j world:
- `pac4j-xxx` is for protocol support: `pac4j-oauth`, `pac4j-cas`, ...
- `yyy-pac4j` is for implementations: `j2e-pac4j`, `play-pac4j`, `vertx-pac4j`...

Notice there is also a `spring-security-pac4j` library following the same convention.

So I prefer to stick to the current naming. And this project is available in the `pac4j` Github organization with the `org.pac4j` groupId. It should be clear for people.

That said, if you are worried about the name sounding like an official extension, I can add a disclaimer at the top of the README: "This is not an OFFICIAL extension".

Other feedback will be also appreciated.

**Comment by snicoll** [comment]
See [this note in the Spring Boot developer guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) for the background of this request. Going on github makes it pretty clear that it's not an official extension so that's fine really.

> `yyy-pac4j` is for implementations

I think that's a mistake because the occurence that said implementation will use that name for their own artifacts is very high. When you list the jars of a project, `spring-webmvc-pac4j` (or `spring-security-pac4j`) is mixed in the middle of something else (the groupId or organization doesn't make a single difference there I am afraid).
